# 3. More on Linear Algebra

**Instructions:**
* go through the notebook and complete the **tasks** .  
* Make sure you understand the examples given!
* When a question allows a free-form answer (e.g., ``what do you observe?``) create a new markdown cell below and answer the question in the notebook.
* ** Save your notebooks when you are done! **

See details on documentation / resources here:
https://learn.gold.ac.uk/mod/page/view.php?id=487982

<hr>
<span style="color:rgb(170,0,0)">**Task 1:**</span> Go through the tutorial on Linear Algebra in python here: http://ml-cheatsheet.readthedocs.io/en/latest/linear_algebra.html.

Paste and run the code from the tutorial in the empty cell below (or create new empty cells below) to get more familiar with the material.

In [10]:
import numpy as np
y = np.array([1,2,3])
x = np.array([2,3,4])
print (y + x) 
print (y - x)
print (y / x)
print (" ")

y = np.array([1,2,3])
x = np.array([2,3,4])
print (np.dot(y,x))
print (" ")

a = np.array([[1,2,3],[4,5,6]])
print (a.shape)
b = np.array([[1,2,3]])
print (b.shape)
print (" ")

a = np.array(
[[1,2],
 [3,4]])
print(a + 1)
print (" ")

a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])

print(a + b)
print(a - b)
print (" ")

a = np.array([[2,3],[2,3]])
b = np.array([[3,4],[5,6]])

# Uses python's multiply operator
print (a * b)
print(" ")

a = np.array([[1, 2],[3, 4]])
print(a.T)
print(" ")

a = np.array([[1, 2]])
print(a.shape)
b = np.array([[3, 4],[5, 6]])
print(b.shape)
print(" ")

# Multiply
mm = np.dot(a,b)
print(mm)
print(mm.shape)
print(" ")

a = np.array([[1],[2]])
b = np.array([[3,4],[5,6]])
c = np.array([[1,2]])

# Same no. of rows
# Different no. of columns
# but a has one column so this works
print(a * b)
# Same no. of columns
# Different no. of rows
# but c has one row so this works
print(b * c)
# Different no. of columns
# Different no. of rows
# but both a and c meet the
# size 1 requirement rule
print(a + c)

[3 5 7]
[-1 -1 -1]
[ 0.5         0.66666667  0.75      ]
 
20
 
(2, 3)
(1, 3)
 
[[2 3]
 [4 5]]
 
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
 
[[ 6 12]
 [10 18]]
 
[[1 3]
 [2 4]]
 
(1, 2)
(2, 2)
 
[[13 16]]
(1, 2)
 
[[ 3  4]
 [10 12]]
[[ 3  8]
 [ 5 12]]
[[2 3]
 [3 4]]


<span style="color:rgb(170,0,0)">**Task 2:**</span> Create the following matrices:
* $X=\begin{bmatrix} 2 & 3 & 4 \\ 1 & 2 &3 \end{bmatrix},Y=\begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 &0\\ 0 & 0 & 1 \end{bmatrix}$
* Multiply X with Y (Z1=X*Y=XY) and print the result.  What do you observe?
* Multiply X with Y transpose (Z2=X*Y.T) and print the result.  What do you observe?
* What can you tell about matrix Y, given Z1 and Z2?

In [13]:
X=np.array([[2,3,4],[1,2,3]])
Y=np.array([[0,1,0],[1,0,0],[0,0,1]])
print (X)
print (Y)

[[2 3 4]
 [1 2 3]]
[[0 1 0]
 [1 0 0]
 [0 0 1]]


<span style="color:rgb(170,0,0)">**Task 3:**</span> Create a 2x2 identity matrix I using the numpy function ``eye(dim)`` 
$$ I=\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} $$

In [15]:
I=np.eye(2,2)
print (I)

[[ 1.  0.]
 [ 0.  1.]]


<span style="color:rgb(170,0,0)">**Task 4:**</span> Multiply (using ``dot``) matrix I with the vector ``x`` defined below. Print the output.  What do you observe?
$$  =Ix$$

In [16]:
x=np.array([2,3])
np.dot(x,I)
print(x)
#Code here

[2 3]


<span style="color:rgb(170,0,0)">**Task 5:**</span> Multiply (using ``dot``) matrix I with the matrix ``X`` defined below. Print the output.  What do you observe? 
$$=IX$$

In [17]:
X=np.array([[2,3],[4,5]])
np.dot(X,I)
print(X)
#Code here

[[2 3]
 [4 5]]


<span style="color:rgb(170,0,0)">**Task 6:**</span> Multiply (using ``dot``) matrix $X$ with the inverse matrix, $X^{-1}$ (use the numpy function ``linalg.inv`` to do so).  What do you observe? $=$XX^{-1}$$


In [21]:
X=np.array([[1,2],[0,1]])
X1=np.linalg.inv(X)
print (X)
print (X1)
print (np.dot(X,X1))
#Code here


[[1 2]
 [0 1]]
[[ 1. -2.]
 [ 0.  1.]]
[[ 1.  0.]
 [ 0.  1.]]
